import {GetGamePageResponse} from "../../models/game.model";

export const gameItemsMock: GetGamePageResponse = [
  {
    id: 345,
    title: "Forge of Empires",
    thumbnail: "https://www.freetogame.com/g/345/thumbnail.jpg",
    short_description:
      "A free to play 2D browser-based online strategy game, become the leader and raise your city.",
    game_url: "https://www.freetogame.com/open/forge-of-empires",
    genre: "Strategy",
    platform: "Web Browser",
    publisher: "InnoGames",
    developer: "InnoGames",
    release_date: "2012-04-17",
    freetogame_profile_url: "https://www.freetogame.com/forge-of-empires",
  },
  {
    id: 525,
    title: "MultiVersus",
    thumbnail: "https://www.freetogame.com/g/525/thumbnail.jpg",
    short_description:
      "The Warner Bros lineup meets Smash in Player First Games’ MultiVersus.",
    game_url: "https://www.freetogame.com/open/multiversus",
    genre: "Fighting",
    platform: "PC (Windows)",
    publisher: "Warner Bros. Games",
    developer: "Player First Games",
    release_date: "2022-07-19",
    freetogame_profile_url: "https://www.freetogame.com/multiversus",
  },
  {
    id: 347,
    title: "Elvenar",
    thumbnail: "https://www.freetogame.com/g/347/thumbnail.jpg",
    short_description:
      "A browser based city-building strategy MMO set in the fantasy world of Elvenar.",
    game_url: "https://www.freetogame.com/open/elvenar",
    genre: "Strategy",
    platform: "Web Browser",
    publisher: "InnoGames",
    developer: "InnoGames",
    release_date: "2015-04-08",
    freetogame_profile_url: "https://www.freetogame.com/elvenar",
  },
  {
    id: 380,
    title: "Dark Orbit Reloaded",
    thumbnail: "https://www.freetogame.com/g/380/thumbnail.jpg",
    short_description:
      "A browser-based 3D space-combat MMO with a massive playerbase!",
    game_url: "https://www.freetogame.com/open/darkorbit",
    genre: "Shooter",
    platform: "Web Browser",
    publisher: "Bigpoint",
    developer: "Bigpoint",
    release_date: "2006-12-11",
    freetogame_profile_url: "https://www.freetogame.com/darkorbit",
  },
  {
    id: 455,
    title: "Eternal Fury",
    thumbnail: "https://www.freetogame.com/g/455/thumbnail.jpg",
    short_description: "A free-to-play ARPG from R2 Games!",
    game_url: "https://www.freetogame.com/open/eternal-fury",
    genre: "MMORPG",
    platform: "Web Browser",
    publisher: "R2 Games",
    developer: "R2 Games",
    release_date: "2019-05-21",
    freetogame_profile_url: "https://www.freetogame.com/eternal-fury",
  },
  {
    id: 212,
    title: "Brawlhalla",
    thumbnail: "https://www.freetogame.com/g/212/thumbnail.jpg",
    short_description:
      "A free-to-play 2D platform fighter inspired by the Smash Bros.",
    game_url: "https://www.freetogame.com/open/brawlhalla",
    genre: "Fighting",
    platform: "PC (Windows)",
    publisher: "Blue Mammoth Games",
    developer: "Blue Mammoth Games",
    release_date: "2015-11-03",
    freetogame_profile_url: "https://www.freetogame.com/brawlhalla",
  },
  {
    id: 350,
    title: "Goodgame Empire",
    thumbnail: "https://www.freetogame.com/g/350/thumbnail.jpg",
    short_description:
      "A free to play medieval strategy browser game. Build you own castle and create a powerful army! ",
    game_url: "https://www.freetogame.com/open/goodgame-empire",
    genre: "Strategy",
    platform: "Web Browser",
    publisher: "Goodgame Studios",
    developer: "Goodgame Studios",
    release_date: "2011-08-14",
    freetogame_profile_url: "https://www.freetogame.com/goodgame-empire",
  },
  {
    id: 559,
    title: "Tales Of Yore",
    thumbnail: "https://www.freetogame.com/g/559/thumbnail.jpg",
    short_description: "A 2D MMORPG with lots of RPG tropes.",
    game_url: "https://www.freetogame.com/open/tales-of-yore",
    genre: "MMORPG",
    platform: "PC (Windows), Web Browser",
    publisher: "Coke And Code",
    developer: "Coke And Code",
    release_date: "2023-08-08",
    freetogame_profile_url: "https://www.freetogame.com/tales-of-yore",
  },
  {
    id: 562,
    title: "Waven",
    thumbnail: "https://www.freetogame.com/g/562/thumbnail.jpg",
    short_description: "A free-to-play online tactical RPG from Ankama.",
    game_url: "https://www.freetogame.com/open/waven",
    genre: "Strategy",
    platform: "PC (Windows)",
    publisher: "Ankama Studio",
    developer: "Ankama Games",
    release_date: "2023-08-16",
    freetogame_profile_url: "https://www.freetogame.com/waven",
  },
  {
    id: 541,
    title: "Marvel Snap",
    thumbnail: "https://www.freetogame.com/g/541/thumbnail.jpg",
    short_description:
      "A fast paced strategy card game set in the Marvel universe.",
    game_url: "https://www.freetogame.com/open/marvel-snap",
    genre: "Card Game",
    platform: "PC (Windows)",
    publisher: "Nuverse",
    developer: "Second Dinner Studios, Inc.",
    release_date: "2022-10-18",
    freetogame_profile_url: "https://www.freetogame.com/marvel-snap",
  },
  {
    id: 524,
    title: "Temperia: Soul of Majestic",
    thumbnail: "https://www.freetogame.com/g/524/thumbnail.jpg",
    short_description:
      "Fans of collectible card games, are you looking for something a bit different from the normal fare? Then a peek at Moonwolf Entertainment and A2 Softworks’ Temperia: Soul of Majestic might be in order.",
    game_url: "https://www.freetogame.com/open/temperia",
    genre: "Card Game",
    platform: "PC (Windows)",
    publisher: "Leonardo Interactive",
    developer: "MoonWolf Entertainment, A2 Softworks",
    release_date: "2022-07-26",
    freetogame_profile_url: "https://www.freetogame.com/temperia",
  },
  {
    id: 532,
    title: "World of Runes",
    thumbnail: "https://www.freetogame.com/g/532/thumbnail.jpg",
    short_description:
      "An adorable anime-style MMO featuring cute pets and collectable cards.",
    game_url: "https://www.freetogame.com/open/world-of-runes",
    genre: "MMORPG",
    platform: "Web Browser",
    publisher: "F5 Game Company Limited",
    developer: "R2 Games",
    release_date: "2022-06-13",
    freetogame_profile_url: "https://www.freetogame.com/world-of-runes",
  },
  {
    id: 550,
    title: "Goose, Goose, DUCK",
    thumbnail: "https://www.freetogame.com/g/550/thumbnail.jpg",
    short_description: "A social deduction game with geese.",
    game_url: "https://www.freetogame.com/open/goose-goose-duck",
    genre: "Strategy",
    platform: "PC (Windows)",
    publisher: "Gaggle Studios, Inc.",
    developer: "Gaggle Studios, Inc.",
    release_date: "2021-10-03",
    freetogame_profile_url: "https://www.freetogame.com/goose-goose-duck",
  },
  {
    id: 500,
    title: "Chroma: Bloom And Blight",
    thumbnail: "https://www.freetogame.com/g/500/thumbnail.jpg",
    short_description:
      "Competitive card game fans have a new, completely free option to add to their list. ",
    game_url: "https://www.freetogame.com/open/chroma-bloom-and-blight",
    genre: "Card Game",
    platform: "PC (Windows)",
    publisher: "WhisperGames",
    developer: "Clarity Games",
    release_date: "2021-01-28",
    freetogame_profile_url:
      "https://www.freetogame.com/chroma-bloom-and-blight",
  },
  {
    id: 463,
    title: "Survivor Legacy",
    thumbnail: "https://www.freetogame.com/g/463/thumbnail.jpg",
    short_description:
      "Survivor Legacy is a free-to-play zombie-themed strategy game from R2 Games.",
    game_url: "https://www.freetogame.com/open/survivor-legacy",
    genre: "Strategy",
    platform: "Web Browser",
    publisher: "R2 Games",
    developer: "GameHollywood",
    release_date: "2020-04-07",
    freetogame_profile_url: "https://www.freetogame.com/survivor-legacy",
  },
  {
    id: 443,
    title: "Ultimate Pirates",
    thumbnail: "https://www.freetogame.com/g/443/thumbnail.jpg",
    short_description:
      "A browser-based strategy MMO published for both desktop and mobile browsers by Gameforge.  ",
    game_url: "https://www.freetogame.com/open/ultimate-pirates",
    genre: "Strategy",
    platform: "Web Browser",
    publisher: "Gameforge",
    developer: "Moonmana",
    release_date: "2019-12-02",
    freetogame_profile_url: "https://www.freetogame.com/ultimate-pirates",
  },
  {
    id: 535,
    title: "Mirage Online Classic",
    thumbnail: "https://www.freetogame.com/g/535/thumbnail.jpg",
    short_description:
      "A browser-based free-to-play spiritual successor to 2001's Mirage Online.",
    game_url: "https://www.freetogame.com/open/mirage-online-classic",
    genre: "MMORPG",
    platform: "Web Browser",
    publisher: "Retrelon Games",
    developer: "Retrelon Games",
    release_date: "2019-12-24",
    freetogame_profile_url: "https://www.freetogame.com/mirage-online-classic",
  },
  {
    id: 440,
    title: "Vampire Empire",
    thumbnail: "https://www.freetogame.com/g/440/thumbnail.jpg",
    short_description:
      "A multiplayer strategy game that focuses on the war between vampires and werewolves. ",
    game_url: "https://www.freetogame.com/open/vampire-empire",
    genre: "Strategy",
    platform: "Web Browser",
    publisher: "R2 Games",
    developer: "F5 Game Company",
    release_date: "2019-11-07",
    freetogame_profile_url: "https://www.freetogame.com/vampire-empire",
  },
  {
    id: 435,
    title: "Battle Breakers",
    thumbnail: "https://www.freetogame.com/g/435/thumbnail.jpg",
    short_description:
      "A multi-platform free-to-play RPG developed and published by Epic Games for PC and Android devices.  ",
    game_url: "https://www.freetogame.com/open/battlebreakers",
    genre: "Strategy",
    platform: "PC (Windows)",
    publisher: "Epic Games",
    developer: "Epic Games",
    release_date: "2019-11-13",
    freetogame_profile_url: "https://www.freetogame.com/battlebreakers",
  },
  {
    id: 468,
    title: "Firestone Idle RPG",
    thumbnail: "https://www.freetogame.com/g/468/thumbnail.jpg",
    short_description:
      "Set in the fantasy world of Alandria, Firestone is an idle RPG in which players are tasked with building the best possible party of heroes and using them to defeat the undead and orcs that plague the world.",
    game_url: "https://www.freetogame.com/open/firestone-idle-rpg",
    genre: "Strategy",
    platform: "Web Browser",
    publisher: "Holyday Studios",
    developer: "Holyday Studios",
    release_date: "2019-09-26",
    freetogame_profile_url: "https://www.freetogame.com/firestone-idle-rpg",
  },
  {
    id: 353,
    title: "Stein.world",
    thumbnail: "https://www.freetogame.com/g/353/thumbnail.jpg",
    short_description:
      "A free-to-play, browser-based online fantasy role \r\nplaying game done in an old-school \r\n16-bit style.",
    game_url: "https://www.freetogame.com/open/steinworld",
    genre: "MMORPG",
    platform: "Web Browser",
    publisher: "PG5-Studio UG",
    developer: "PG5-Studio UG",
    release_date: "2019-04-24",
    freetogame_profile_url: "https://www.freetogame.com/steinworld",
  },
  {
    id: 438,
    title: "Kards",
    thumbnail: "https://www.freetogame.com/g/438/thumbnail.jpg",
    short_description:
      "A free-to-play collectible World War II card game from developer 1939 Games.",
    game_url: "https://www.freetogame.com/open/kards",
    genre: "Card Game",
    platform: "PC (Windows)",
    publisher: "1939 Games",
    developer: "1939 Games",
    release_date: "2019-04-12",
    freetogame_profile_url: "https://www.freetogame.com/kards",
  },
  {
    id: 457,
    title: "The Third Age",
    thumbnail: "https://www.freetogame.com/g/457/thumbnail.jpg",
    short_description:
      "A free-to-play browser-based Strategy MMO game focused on story-based PvE gameplay!",
    game_url: "https://www.freetogame.com/open/the-third-age",
    genre: "Strategy",
    platform: "Web Browser",
    publisher: "R2 Games",
    developer: "R2 Games",
    release_date: "2019-04-29",
    freetogame_profile_url: "https://www.freetogame.com/the-third-age",
  },
  {
    id: 31,
    title: "Cosmos Invictus",
    thumbnail: "https://www.freetogame.com/g/31/thumbnail.jpg",
    short_description:
      "A strategic collectible card game developed and published by Pegnio Ltd. ",
    game_url: "https://www.freetogame.com/open/cosmos-invictus",
    genre: "Card Game",
    platform: "PC (Windows)",
    publisher: "Pegnio Ltd",
    developer: "Pegnio Ltd",
    release_date: "2018-06-27",
    freetogame_profile_url: "https://www.freetogame.com/cosmos-invictus",
  },
  {
    id: 460,
    title: "Empire: World War 3",
    thumbnail: "https://www.freetogame.com/g/460/thumbnail.jpg",
    short_description:
      "A free-to-play browser-based action packed strategy game from the developer of Legends of Honor.",
    game_url: "https://www.freetogame.com/open/empireww3",
    genre: "Strategy",
    platform: "Web Browser",
    publisher: "Goodgame Studios",
    developer: "Goodgame Studios",
    release_date: "2018-06-28",
    freetogame_profile_url: "https://www.freetogame.com/empireww3",
  },
  {
    id: 543,
    title: "Battle Arena Heroes Adventure",
    thumbnail: "https://www.freetogame.com/g/543/thumbnail.jpg",
    short_description: "A MOBA with RPG elements.",
    game_url: "https://www.freetogame.com/open/battle-arena-heroes-adventure",
    genre: "Strategy",
    platform: "Web Browser",
    publisher: "Espirit Games",
    developer: "Espirit Games",
    release_date: "2018-03-19",
    freetogame_profile_url:
      "https://www.freetogame.com/battle-arena-heroes-adventure",
  },
  {
    id: 49,
    title: "Dead Maze",
    thumbnail: "https://www.freetogame.com/g/49/thumbnail.jpg",
    short_description: "A free-to-play 2D isometric MMO full of zombies. ",
    game_url: "https://www.freetogame.com/open/dead-maze",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "801",
    developer: "801",
    release_date: "2018-02-13",
    freetogame_profile_url: "https://www.freetogame.com/dead-maze",
  },
  {
    id: 22,
    title: "Wild Terra Online",
    thumbnail: "https://www.freetogame.com/g/22/thumbnail.jpg",
    short_description:
      "A medieval sandbox MMO designed with core players in mind. ",
    game_url: "https://www.freetogame.com/open/wild-terra-online",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "Juvty Worlds Ltd.",
    developer: "Juvty Worlds Ltd.",
    release_date: "2017-12-18",
    freetogame_profile_url: "https://www.freetogame.com/wild-terra-online",
  },
  {
    id: 322,
    title: "La Tale Evolved",
    thumbnail: "https://www.freetogame.com/g/322/thumbnail.jpg",
    short_description:
      "A 2D side-scrolling fantasy MMORPG with anime-inspired graphics.",
    game_url: "https://www.freetogame.com/open/la-tale",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "Papaya Play",
    developer: "Actoz Soft",
    release_date: "2017-11-17",
    freetogame_profile_url: "https://www.freetogame.com/la-tale",
  },
  {
    id: 58,
    title: "The Ultimatest Battle",
    thumbnail: "https://www.freetogame.com/g/58/thumbnail.jpg",
    short_description:
      "A free-to-play 2D platform game that pits two teams of players against each other in a variety of modes. ",
    game_url: "https://www.freetogame.com/open/the-ultimatest-battle",
    genre: "Fighting",
    platform: "PC (Windows)",
    publisher: "Ediogames",
    developer: "Ediogames",
    release_date: "2017-09-12",
    freetogame_profile_url: "https://www.freetogame.com/the-ultimatest-battle",
  },
  {
    id: 354,
    title: "Gods Origin Online",
    thumbnail: "https://www.freetogame.com/g/354/thumbnail.jpg",
    short_description:
      "A free-to-play browser-based RPG from VivaGames in which players take on the role of human summoners that call deities from the Astral Realm back in time. ",
    game_url: "https://www.freetogame.com/open/gods-origin",
    genre: "MMORPG",
    platform: "Web Browser",
    publisher: "VivaGame",
    developer: "VivaGame",
    release_date: "2017-08-29",
    freetogame_profile_url: "https://www.freetogame.com/gods-origin",
  },
  {
    id: 65,
    title: "Pixel Worlds",
    thumbnail: "https://www.freetogame.com/g/65/thumbnail.jpg",
    short_description:
      "A free-to-play, side-scroller MMO sandbox game developed and published by Kukouri Mobile Entertainment. ",
    game_url: "https://www.freetogame.com/open/pixel-worlds",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "Kukouri Mobile Entertainment ",
    developer: "Kukouri Mobile Entertainment ",
    release_date: "2017-06-09",
    freetogame_profile_url: "https://www.freetogame.com/pixel-worlds",
  },
  {
    id: 67,
    title: "Awesomenauts",
    thumbnail: "https://www.freetogame.com/g/67/thumbnail.jpg",
    short_description: "A 3v3 2D battle arena Developed by Ronimo games.",
    game_url: "https://www.freetogame.com/open/awesomenauts",
    genre: "MOBA",
    platform: "PC (Windows)",
    publisher: "Ronimo Games",
    developer: "Ronimo Games",
    release_date: "2017-05-24",
    freetogame_profile_url: "https://www.freetogame.com/awesomenauts",
  },
  {
    id: 72,
    title: "Krosmaga",
    thumbnail: "https://www.freetogame.com/g/72/thumbnail.jpg",
    short_description:
      "A free-to-play CCG/tower defense hybrid developed \r\nby Ankama Studio and published by \r\nAnkama Games. ",
    game_url: "https://www.freetogame.com/open/krosmaga",
    genre: "Card Game",
    platform: "PC (Windows)",
    publisher: "Ankama Games",
    developer: "Ankama Studio",
    release_date: "2017-04-12",
    freetogame_profile_url: "https://www.freetogame.com/krosmaga",
  },
  {
    id: 421,
    title: "Therian Saga",
    thumbnail: "https://www.freetogame.com/g/421/thumbnail.jpg",
    short_description:
      "A browser-based sandbox MMORPG with a complex crafting system.",
    game_url: "https://www.freetogame.com/open/therian-saga",
    genre: "MMORPG",
    platform: "PC (Windows), Web Browser",
    publisher: "Gameforge",
    developer: "Virtys",
    release_date: "2017-03-27",
    freetogame_profile_url: "https://www.freetogame.com/therian-saga",
  },
  {
    id: 69,
    title: "Cabals: Card Blitz",
    thumbnail: "https://www.freetogame.com/g/69/thumbnail.jpg",
    short_description:
      "A free-to-play game developed by Kyy Games and published by BISBOG SA. ",
    game_url: "https://www.freetogame.com/open/cabals-card-blitz",
    genre: "Card Game",
    platform: "PC (Windows)",
    publisher: "BISBOG SA",
    developer: "Kyy Games",
    release_date: "2017-02-08",
    freetogame_profile_url: "https://www.freetogame.com/cabals-card-blitz",
  },
  {
    id: 99,
    title: "Star Crusade",
    thumbnail: "https://www.freetogame.com/g/99/thumbnail.jpg",
    short_description:
      "A free-to-play sci-fi themed collectable card game developed and published by ZiMAD inc. ",
    game_url: "https://www.freetogame.com/open/star-crusade",
    genre: "Card Game",
    platform: "PC (Windows)",
    publisher: "ZiMAD, Inc.",
    developer: "ZiMAD, Inc.",
    release_date: "2016-09-08",
    freetogame_profile_url: "https://www.freetogame.com/star-crusade",
  },
  {
    id: 365,
    title: "Naruto Online",
    thumbnail: "https://www.freetogame.com/g/365/thumbnail.jpg",
    short_description:
      "A free-to-play MMO based on the popular anime series and manga, developed \r\nby Bandai Namco Entertainment. ",
    game_url: "https://www.freetogame.com/open/naruto-online",
    genre: "MMORPG",
    platform: "Web Browser",
    publisher: "OAS Games",
    developer: "Bandai Namco",
    release_date: "2016-07-20",
    freetogame_profile_url: "https://www.freetogame.com/naruto-online",
  },
  {
    id: 118,
    title: "Starbreak",
    thumbnail: "https://www.freetogame.com/g/118/thumbnail.jpg",
    short_description:
      "A Roguelike MMORPG with MetroidVania-style platformer \r\ngameplay! Castlevania and Metroid fans will \r\nlove this game! ",
    game_url: "https://www.freetogame.com/open/starbreak",
    genre: "MMORPG",
    platform: "PC (Windows), Web Browser",
    publisher: "Crunchy Games",
    developer: "Crunchy Games",
    release_date: "2016-05-10",
    freetogame_profile_url: "https://www.freetogame.com/starbreak",
  },
  {
    id: 119,
    title: "Fantasy Tales Online",
    thumbnail: "https://www.freetogame.com/g/119/thumbnail.jpg",
    short_description:
      "A free-to-play, retro MMO featuring puzzles, a rich crafting system and Randomly generated dungeons! ",
    game_url: "https://www.freetogame.com/open/fantasy-tales-online",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "Cold Tea Studio ",
    developer: "Cold Tea Studio ",
    release_date: "2016-05-06",
    freetogame_profile_url: "https://www.freetogame.com/fantasy-tales-online",
  },
  {
    id: 370,
    title: "Dragon Blood",
    thumbnail: "https://www.freetogame.com/g/370/thumbnail.jpg",
    short_description:
      "A free-to-play browser MMORPG from 101XP, you'll harness your unique power and the blood of dragons that flows through your veins! ",
    game_url: "https://www.freetogame.com/open/dragon-blood",
    genre: "MMORPG",
    platform: "Web Browser",
    publisher: "101XP",
    developer: "101XP",
    release_date: "2016-04-16",
    freetogame_profile_url: "https://www.freetogame.com/dragon-blood",
  },
  {
    id: 117,
    title: "Astral Heroes",
    thumbnail: "https://www.freetogame.com/g/117/thumbnail.jpg",
    short_description:
      "A free-to-play collectable card game from the creators of Astral Masters. ",
    game_url: "https://www.freetogame.com/open/astral-heroes",
    genre: "Card Game",
    platform: "PC (Windows)",
    publisher: "Apus Software",
    developer: "Apus Software",
    release_date: "2016-03-15",
    freetogame_profile_url: "https://www.freetogame.com/astral-heroes",
  },
  {
    id: 136,
    title: "VEGA Conflict",
    thumbnail: "https://www.freetogame.com/g/136/thumbnail.jpg",
    short_description: "A Cross-Platform free to play 2D sci-fi strategy MMO.",
    game_url: "https://www.freetogame.com/open/vega-conflict",
    genre: "Strategy",
    platform: "PC (Windows)",
    publisher: "KIXEYE",
    developer: "KIXEYE",
    release_date: "2015-12-15",
    freetogame_profile_url: "https://www.freetogame.com/vega-conflict",
  },
  {
    id: 139,
    title: "Immortal Empire",
    thumbnail: "https://www.freetogame.com/g/139/thumbnail.jpg",
    short_description:
      "A free to play multiplayer strategy RPG developed by Tactic Studios.",
    game_url: "https://www.freetogame.com/open/immortal-empire",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "Tactic Studios Inc.",
    developer: "Tactic Studios Inc.",
    release_date: "2015-12-03",
    freetogame_profile_url: "https://www.freetogame.com/immortal-empire",
  },
  {
    id: 346,
    title: "One Piece Online 2",
    thumbnail: "https://www.freetogame.com/g/346/thumbnail.jpg",
    short_description:
      "A free-to-play, browser-based 2D MMORPG based on the immensely popular One Piece franchise.",
    game_url: "https://www.freetogame.com/open/one-piece-online-2",
    genre: "MMORPG",
    platform: "Web Browser",
    publisher: "JoyGames",
    developer: "JoyGames",
    release_date: "2015-09-25",
    freetogame_profile_url: "https://www.freetogame.com/one-piece-online-2",
  },
  {
    id: 383,
    title: "Legends of Honor",
    thumbnail: "https://www.freetogame.com/g/383/thumbnail.jpg",
    short_description:
      "A free to play browser based medieval fantasy 2D MMORTS.",
    game_url: "https://www.freetogame.com/open/legends-of-honor",
    genre: "Strategy",
    platform: "Web Browser",
    publisher: "Goodgame Empire",
    developer: "Goodgame Studios",
    release_date: "2015-08-20",
    freetogame_profile_url: "https://www.freetogame.com/legends-of-honor",
  },
  {
    id: 384,
    title: "Felspire",
    thumbnail: "https://www.freetogame.com/g/384/thumbnail.jpg",
    short_description:
      "A free-to-play 2D browser-based fantasy MMORPG with plenty of dungeons and world bosses to slay.",
    game_url: "https://www.freetogame.com/open/felspire",
    genre: "MMORPG",
    platform: "Web Browser",
    publisher: "37Games",
    developer: "37Games Entertainment",
    release_date: "2015-08-07",
    freetogame_profile_url: "https://www.freetogame.com/felspire",
  },
  {
    id: 163,
    title: "Card Hunter",
    thumbnail: "https://www.freetogame.com/g/163/thumbnail.jpg",
    short_description:
      "A free online collectible card game which blends together role-playing, card play and tactical combat. ",
    game_url: "https://www.freetogame.com/open/card-hunter",
    genre: "Card Game",
    platform: "PC (Windows), Web Browser",
    publisher: "Blue Manchu",
    developer: "Blue Manchu",
    release_date: "2015-07-14",
    freetogame_profile_url: "https://www.freetogame.com/card-hunter",
  },
  {
    id: 386,
    title: "Aberoth",
    thumbnail: "https://www.freetogame.com/g/386/thumbnail.jpg",
    short_description:
      "A free to play 8-bit MMORPG with retro graphics and MUD-like interface.",
    game_url: "https://www.freetogame.com/open/aberoth",
    genre: " MMORPG",
    platform: "Web Browser",
    publisher: "Jarbit",
    developer: "Jarbit",
    release_date: "2015-07-17",
    freetogame_profile_url: "https://www.freetogame.com/aberoth",
  },
  {
    id: 104,
    title: "Fallout Shelter",
    thumbnail: "https://www.freetogame.com/g/104/thumbnail.jpg",
    short_description:
      "A free-to-play simulation game based on Bethesda Game Studios' popular Fallout franchise. ",
    game_url: "https://www.freetogame.com/open/fallout-shelter",
    genre: "Strategy",
    platform: "PC (Windows)",
    publisher: "Bethesda Game Studios",
    developer: "Bethesda Game Studios",
    release_date: "2015-06-14",
    freetogame_profile_url: "https://www.freetogame.com/fallout-shelter",
  },
  {
    id: 391,
    title: "Star Trek: Alien Domain",
    thumbnail: "https://www.freetogame.com/g/391/thumbnail.jpg",
    short_description:
      "A free to play browser based 2D strategy MMO set in the Stark Trek universe.",
    game_url: "https://www.freetogame.com/open/star-trek-alien-domain",
    genre: "Strategy",
    platform: "Web Browser",
    publisher: "GameSamba",
    developer: "GameSamba",
    release_date: "2015-04-07",
    freetogame_profile_url: "https://www.freetogame.com/star-trek-alien-domain",
  },
  {
    id: 177,
    title: "Dungeon Fighter Online",
    thumbnail: "https://www.freetogame.com/g/177/thumbnail.jpg",
    short_description:
      "A free to play arcade-style side-scrolling action game mixed with RPG elements.",
    game_url: "https://www.freetogame.com/open/dungeon-fighter-online",
    genre: "Fighting",
    platform: "PC (Windows)",
    publisher: "Neople",
    developer: "Neople (Subsidiary of Nexon)",
    release_date: "2015-03-24",
    freetogame_profile_url: "https://www.freetogame.com/dungeon-fighter-online",
  },
  {
    id: 179,
    title: "Transformice",
    thumbnail: "https://www.freetogame.com/g/179/thumbnail.jpg",
    short_description: "A cute little free-to-play MMO platformer.",
    game_url: "https://www.freetogame.com/open/transformice",
    genre: "Fantasy",
    platform: "PC (Windows), Web Browser",
    publisher: "Atelier 801",
    developer: "Atelier 801",
    release_date: "2015-01-30",
    freetogame_profile_url: "https://www.freetogame.com/transformice",
  },
  {
    id: 181,
    title: "8BitMMO",
    thumbnail: "https://www.freetogame.com/g/181/thumbnail.jpg",
    short_description:
      "A free to play retro­-style 2D MMO and a giant construction sandbox! ",
    game_url: "https://www.freetogame.com/open/8bitmmo",
    genre: "MMORPG",
    platform: "PC (Windows), Web Browser",
    publisher: "Archive Entertainment ",
    developer: "Archive Entertainment ",
    release_date: "2015-01-26",
    freetogame_profile_url: "https://www.freetogame.com/8bitmmo",
  },
  {
    id: 373,
    title: "StarColony",
    thumbnail: "https://www.freetogame.com/g/373/thumbnail.jpg",
    short_description:
      "A free-to-play browser MMO strategy game that puts you in command of a rapidly growing city on a dangerous alien world.",
    game_url: "https://www.freetogame.com/open/starcolony",
    genre: "Strategy",
    platform: "Web Browser",
    publisher: "Eiyland LLC",
    developer: "Eiyland LLC",
    release_date: "2015-01-01",
    freetogame_profile_url: "https://www.freetogame.com/starcolony",
  },
  {
    id: 394,
    title: "One Piece Online",
    thumbnail: "https://www.freetogame.com/g/394/thumbnail.jpg",
    short_description: "One Piece Online is a 2D Tower Defense Action MMO! ",
    game_url: "https://www.freetogame.com/open/one-piece-online",
    genre: "MMORPG",
    platform: "Web Browser",
    publisher: "JoyGames",
    developer: "JoyGames",
    release_date: "2015-01-22",
    freetogame_profile_url: "https://www.freetogame.com/one-piece-online",
  },
  {
    id: 399,
    title: "Siegelord",
    thumbnail: "https://www.freetogame.com/g/399/thumbnail.jpg",
    short_description:
      "A free to play 2D medieval fantasy browser-based MMORTS.",
    game_url: "https://www.freetogame.com/open/siegelord",
    genre: "Strategy",
    platform: "Web Browser",
    publisher: "37Games Entertainment",
    developer: "37Games Entertainment",
    release_date: "2014-12-19",
    freetogame_profile_url: "https://www.freetogame.com/siegelord",
  },
  {
    id: 187,
    title: "Pox Nora",
    thumbnail: "https://www.freetogame.com/g/187/thumbnail.jpg",
    short_description:
      "A multiplayer online game that combines a collectible card game with a turn-based strategy game.",
    game_url: "https://www.freetogame.com/open/pox-nora",
    genre: "Card Game",
    platform: "PC (Windows)",
    publisher: "Desert Owl Games LLC ",
    developer: "Desert Owl Games LLC ",
    release_date: "2014-10-15",
    freetogame_profile_url: "https://www.freetogame.com/pox-nora",
  },
  {
    id: 192,
    title: "WAKFU",
    thumbnail: "https://www.freetogame.com/g/192/thumbnail.jpg",
    short_description:
      "A 2D tactical turn-based fantasy MMORPG developed by Ankama Games, in conjunction with Square Enix.",
    game_url: "https://www.freetogame.com/open/wakfu",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "Ankama Games",
    developer: "Ankama Studio",
    release_date: "2014-09-19",
    freetogame_profile_url: "https://www.freetogame.com/wakfu",
  },
  {
    id: 404,
    title: "Tribal Wars 2",
    thumbnail: "https://www.freetogame.com/g/404/thumbnail.jpg",
    short_description:
      "The sequel to the classic city-building strategy game Tribal Wars! ",
    game_url: "https://www.freetogame.com/open/tribal-wars-2",
    genre: "Strategy",
    platform: "Web Browser",
    publisher: "InnoGames",
    developer: "InnoGames",
    release_date: "2014-09-02",
    freetogame_profile_url: "https://www.freetogame.com/tribal-wars-2",
  },
  {
    id: 348,
    title: "Bleach Online",
    thumbnail: "https://www.freetogame.com/g/348/thumbnail.jpg",
    short_description:
      "A free to play 2D browser based MMORPG based on Bleach, the popular manga and anime series.",
    game_url: "https://www.freetogame.com/open/bleach-online",
    genre: "MMORPG",
    platform: "Web Browser",
    publisher: "GoGames",
    developer: "GoGames",
    release_date: "2014-07-14",
    freetogame_profile_url: "https://www.freetogame.com/bleach-online",
  },
  {
    id: 215,
    title: "Hex",
    thumbnail: "https://www.freetogame.com/g/215/thumbnail.jpg",
    short_description:
      "HEX combines roleplaying aspects of a MMO with the collectible and strategic gameplay of a Trading Card Game.",
    game_url: "https://www.freetogame.com/open/hex",
    genre: "Card Game",
    platform: "PC (Windows)",
    publisher: "Hex Entertainment, Gameforge",
    developer: "Cryptozoic Entertainment",
    release_date: "2014-04-11",
    freetogame_profile_url: "https://www.freetogame.com/hex",
  },
  {
    id: 405,
    title: "Pocket Starships",
    thumbnail: "https://www.freetogame.com/g/405/thumbnail.jpg",
    short_description:
      "A free-to-play cross-platform space combat MMO from SPYR games.",
    game_url: "https://www.freetogame.com/open/pocket-starships",
    genre: "Strategy",
    platform: "Web Browser",
    publisher: "Spyr",
    developer: "Spyr",
    release_date: "0000-00-00",
    freetogame_profile_url: "https://www.freetogame.com/pocket-starships",
  },
  {
    id: 409,
    title: "Sparta: War of Empires",
    thumbnail: "https://www.freetogame.com/g/409/thumbnail.jpg",
    short_description:
      "A 2D browser-based MMORTS in which players must exercise their city-management skills to construct and upgrade different structures and troops.",
    game_url: "https://www.freetogame.com/open/sparta-war-empires",
    genre: "Strategy",
    platform: "Web Browser",
    publisher: "Plarium",
    developer: "Plarium",
    release_date: "2014-03-13",
    freetogame_profile_url: "https://www.freetogame.com/sparta-war-empires",
  },
  {
    id: 424,
    title: "Crystal Saga",
    thumbnail: "https://www.freetogame.com/g/424/thumbnail.jpg",
    short_description:
      "A free to play 2D browser-based MMORPG that allows players to explore the land of Vidalia.",
    game_url: "https://www.freetogame.com/open/crystal-saga",
    genre: "MMORPG",
    platform: "Web Browser",
    publisher: "Aeria, R2Games",
    developer: "R2Games",
    release_date: "2013-11-20",
    freetogame_profile_url: "https://www.freetogame.com/crystal-saga",
  },
  {
    id: 411,
    title: "Soldiers Inc.",
    thumbnail: "https://www.freetogame.com/g/411/thumbnail.jpg",
    short_description: "A free to play 2D top-down browser based MMORTS game.",
    game_url: "https://www.freetogame.com/open/soldiers-inc",
    genre: "Strategy",
    platform: "Web Browser",
    publisher: "Plarium Games",
    developer: "Plarium Games",
    release_date: "2013-08-01",
    freetogame_profile_url: "https://www.freetogame.com/soldiers-inc",
  },
  {
    id: 412,
    title: "Nords: Heroes of the North",
    thumbnail: "https://www.freetogame.com/g/412/thumbnail.jpg",
    short_description:
      "A free to play browser-based 2D strategy MMO game with Elves, Orcs, Dragons and more.",
    game_url: "https://www.freetogame.com/open/nords-heroes-north",
    genre: "Strategy",
    platform: "Web Browser",
    publisher: "Plarium Games",
    developer: "Plarium Games",
    release_date: "2013-08-01",
    freetogame_profile_url: "https://www.freetogame.com/nords-heroes-north",
  },
  {
    id: 240,
    title: "Epic Cards Battle",
    thumbnail: "https://www.freetogame.com/g/240/thumbnail.jpg",
    short_description:
      "A free to play online strategic trading card game with dozens of cards and five factions. ",
    game_url: "https://www.freetogame.com/open/epic-card-battle",
    genre: "Card Game",
    platform: "PC (Windows)",
    publisher: "momoStorm Entertainment",
    developer: "momoStorm",
    release_date: "2013-01-29",
    freetogame_profile_url: "https://www.freetogame.com/epic-card-battle",
  },
  {
    id: 414,
    title: "Rail Nation",
    thumbnail: "https://www.freetogame.com/g/414/thumbnail.jpg",
    short_description:
      "A free to play 2D browser-based train simulation strategy MMO game.",
    game_url: "https://www.freetogame.com/open/rail-nation",
    genre: "Strategy",
    platform: "Web Browser",
    publisher: "Bright Future",
    developer: "Travian Games",
    release_date: "2013-01-13",
    freetogame_profile_url: "https://www.freetogame.com/rail-nation",
  },
  {
    id: 415,
    title: "Stormfall: Age of War",
    thumbnail: "https://www.freetogame.com/g/415/thumbnail.jpg",
    short_description:
      "A free to play 2D top-down browser MMORTS featuring castle building, resource management and PvP battles.",
    game_url: "https://www.freetogame.com/open/stormfall-age-war",
    genre: "Strategy",
    platform: "Web Browser",
    publisher: "Plarium",
    developer: "Plarium",
    release_date: "2012-11-01",
    freetogame_profile_url: "https://www.freetogame.com/stormfall-age-war",
  },
  {
    id: 349,
    title: "Big Farm",
    thumbnail: "https://www.freetogame.com/g/349/thumbnail.jpg",
    short_description: "A friendly browser-based farming simulation MMO game!",
    game_url: "https://www.freetogame.com/open/big-farm",
    genre: "Strategy",
    platform: "Web Browser",
    publisher: "GoodGame Studios",
    developer: "GoodGame Studios",
    release_date: "2012-10-29",
    freetogame_profile_url: "https://www.freetogame.com/big-farm",
  },
  {
    id: 416,
    title: "Wartune",
    thumbnail: "https://www.freetogame.com/g/416/thumbnail.jpg",
    short_description:
      "A 2D browser-based Strategy MMORPG with classic turn based RPG features.",
    game_url: "https://www.freetogame.com/open/wartune",
    genre: "MMORPG",
    platform: "Web Browser",
    publisher: "R2 Games",
    developer: "7Th Road",
    release_date: "2012-10-25",
    freetogame_profile_url: "https://www.freetogame.com/wartune",
  },
  {
    id: 418,
    title: "The Settlers Online",
    thumbnail: "https://www.freetogame.com/g/418/thumbnail.jpg",
    short_description:
      "A free to play city building MMORTS based on the popular Settlers series.",
    game_url: "https://www.freetogame.com/open/the-settlers-online",
    genre: "Strategy",
    platform: "Web Browser",
    publisher: "Ubisoft",
    developer: "Blue Byte",
    release_date: "2012-09-11",
    freetogame_profile_url: "https://www.freetogame.com/the-settlers-online",
  },
  {
    id: 249,
    title: "RPG MO",
    thumbnail: "https://www.freetogame.com/g/249/thumbnail.jpg",
    short_description:
      "A nostalgic free MMORPG reminiscent of old-school RPG's like Ultima and Runescape.",
    game_url: "https://www.freetogame.com/open/rpg-mo",
    genre: "MMORPG",
    platform: "PC (Windows), Web Browser",
    publisher: "Marxnet",
    developer: "Marxnet",
    release_date: "2012-07-18",
    freetogame_profile_url: "https://www.freetogame.com/rpg-mo",
  },
  {
    id: 255,
    title: "Stronghold Kingdoms",
    thumbnail: "https://www.freetogame.com/g/255/thumbnail.jpg",
    short_description:
      "A strategy based building/warfare game based on the long running Strongholds PC game series.",
    game_url: "https://www.freetogame.com/open/stronghold-kingdoms",
    genre: "Strategy",
    platform: "Web Browser",
    publisher: "FireFly Studios",
    developer: "FireFly Studios",
    release_date: "2012-02-28",
    freetogame_profile_url: "https://www.freetogame.com/stronghold-kingdoms",
  },
  {
    id: 256,
    title: "Realm of the Mad God",
    thumbnail: "https://www.freetogame.com/g/256/thumbnail.jpg",
    short_description:
      "A fast paced 2d free to play MMO shooter game with a retro 8-bit style.",
    game_url: "https://www.freetogame.com/open/realm-mad-god",
    genre: "MMORPG",
    platform: "PC (Windows), Web Browser",
    publisher: "Kabam",
    developer: "Wild Shadow Studios",
    release_date: "2012-02-21",
    freetogame_profile_url: "https://www.freetogame.com/realm-mad-god",
  },
  {
    id: 422,
    title: "Pirates: Tides of Fortune",
    thumbnail: "https://www.freetogame.com/g/422/thumbnail.jpg",
    short_description:
      "A free to play browser-based 2D MMORTS for people who are fans of pirates!",
    game_url: "https://www.freetogame.com/open/pirates-tides-fortune",
    genre: "Strategy",
    platform: "Web Browser",
    publisher: "Plarium Games",
    developer: "Plarium Games",
    release_date: "2012-02-12",
    freetogame_profile_url: "https://www.freetogame.com/pirates-tides-fortune",
  },
  {
    id: 425,
    title: "Grepolis",
    thumbnail: "https://www.freetogame.com/g/425/thumbnail.jpg",
    short_description:
      "A free to play browser-based strategy MMORTS set in Ancient Greece.",
    game_url: "https://www.freetogame.com/open/grepolis",
    genre: "Strategy",
    platform: "Web Browser",
    publisher: "InnoGames",
    developer: "InnoGames",
    release_date: "2009-12-08",
    freetogame_profile_url: "https://www.freetogame.com/grepolis",
  },
  {
    id: 402,
    title: "Might And Magic Heroes Online",
    thumbnail: "https://www.freetogame.com/g/402/thumbnail.jpg",
    short_description:
      "A free-to-play MMO strategy RPG game in which you control powerful Heroes! ",
    game_url: "https://www.freetogame.com/open/might-magic-heroes-online",
    genre: "MMORPG",
    platform: "Web Browser",
    publisher: "Ubisoft",
    developer: "Ubisoft Blue Byte, Related Designs",
    release_date: "2009-09-03",
    freetogame_profile_url:
      "https://www.freetogame.com/might-magic-heroes-online",
  },
  {
    id: 426,
    title: "AdventureQuest Worlds",
    thumbnail: "https://www.freetogame.com/g/426/thumbnail.jpg",
    short_description:
      "A free-to-play 2D fantasy browser MMORPG. There are no downloads or software to install! ",
    game_url: "https://www.freetogame.com/open/adventurequest-worlds",
    genre: "MMORPG",
    platform: "Web Browser",
    publisher: "Artix Entertainment",
    developer: "Artix Entertainment",
    release_date: "2008-10-10",
    freetogame_profile_url: "https://www.freetogame.com/adventurequest-worlds",
  },
  {
    id: 428,
    title: "Ikariam",
    thumbnail: "https://www.freetogame.com/g/428/thumbnail.jpg",
    short_description:
      "A free to play browser-based city-building strategy game by GameForge.",
    game_url: "https://www.freetogame.com/open/ikariam",
    genre: "Strategy",
    platform: "Web Browser",
    publisher: "GameForge",
    developer: "GameForge",
    release_date: "2008-03-31",
    freetogame_profile_url: "https://www.freetogame.com/ikariam",
  },
  {
    id: 308,
    title: "Angels Online",
    thumbnail: "https://www.freetogame.com/g/308/thumbnail.jpg",
    short_description: "A cute anime MMORPG with a good selection of classes.",
    game_url: "https://www.freetogame.com/open/angels-online",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "I Got Games",
    developer: "UserJoy Technology",
    release_date: "2007-12-01",
    freetogame_profile_url: "https://www.freetogame.com/angels-online",
  },
  {
    id: 313,
    title: "Teeworlds",
    thumbnail: "https://www.freetogame.com/g/313/thumbnail.jpg",
    short_description:
      "A free to play retro multiplayer online shooter where you can even design your own maps!",
    game_url: "https://www.freetogame.com/open/teeworlds",
    genre: "Shooter",
    platform: "PC (Windows)",
    publisher: "Teeworlds Team ",
    developer: "Teeworlds Team ",
    release_date: "2007-05-27",
    freetogame_profile_url: "https://www.freetogame.com/teeworlds",
  },
  {
    id: 351,
    title: "Grand Prix Racing Online",
    thumbnail: "https://www.freetogame.com/g/351/thumbnail.jpg",
    short_description: "A free-to-play web-based motorsport management game.",
    game_url: "https://www.freetogame.com/open/gpro",
    genre: "Strategy",
    platform: "Web Browser",
    publisher: "GPRO.net",
    developer: "GPRO.net",
    release_date: "2006-08-01",
    freetogame_profile_url: "https://www.freetogame.com/gpro",
  },
  {
    id: 429,
    title: "Astro Empires",
    thumbnail: "https://www.freetogame.com/g/429/thumbnail.jpg",
    short_description:
      "A text-based sci-fi strategy and diplomacy MMO Game in a persistent universe.",
    game_url: "https://www.freetogame.com/open/astro-empires",
    genre: "Strategy",
    platform: "Web Browser",
    publisher: "Cybertopia",
    developer: "Cybertopia",
    release_date: "0000-00-00",
    freetogame_profile_url: "https://www.freetogame.com/astro-empires",
  },
  {
    id: 430,
    title: "Urban Rivals",
    thumbnail: "https://www.freetogame.com/g/430/thumbnail.jpg",
    short_description:
      "A free to play browser based card-game with a high player base and comic-book inspired world!",
    game_url: "https://www.freetogame.com/open/urban-rivals",
    genre: "Card Game",
    platform: "Web Browser",
    publisher: "Boostr ",
    developer: "Acute Mobile",
    release_date: "2006-01-17",
    freetogame_profile_url: "https://www.freetogame.com/urban-rivals",
  },
  {
    id: 431,
    title: "Imperia Online",
    thumbnail: "https://www.freetogame.com/g/431/thumbnail.jpg",
    short_description:
      "A 2D free-to-play browser-based Medieval MMORTS, Train soldiers and raise an Empire.",
    game_url: "https://www.freetogame.com/open/imperia-online",
    genre: "Strategy",
    platform: "Web Browser",
    publisher: "Imperia Online Ltd.",
    developer: "Imperia Online Ltd.",
    release_date: "2005-08-23",
    freetogame_profile_url: "https://www.freetogame.com/imperia-online",
  },
  {
    id: 325,
    title: "MapleStory",
    thumbnail: "https://www.freetogame.com/g/325/thumbnail.jpg",
    short_description:
      "A popular free-to-play 2D side-scrolling MMORPG with tons of quests, and a huge game world!",
    game_url: "https://www.freetogame.com/open/maplestory",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "Nexon",
    developer: "Wizet",
    release_date: "2005-05-11",
    freetogame_profile_url: "https://www.freetogame.com/maplestory",
  },
  {
    id: 328,
    title: "Dofus",
    thumbnail: "https://www.freetogame.com/g/328/thumbnail.jpg",
    short_description:
      "A 2D MMORPG with tons of different classes and a tactical combat system.",
    game_url: "https://www.freetogame.com/open/dofus",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "Ankama Games",
    developer: "Ankama Games",
    release_date: "2004-09-01",
    freetogame_profile_url: "https://www.freetogame.com/dofus",
  },
  {
    id: 352,
    title: "Travian",
    thumbnail: "https://www.freetogame.com/g/352/thumbnail.jpg",
    short_description:
      "A popular browser-based multiplayer online strategy \r\ngame.",
    game_url: "https://www.freetogame.com/open/travian",
    genre: "Strategy",
    platform: "Web Browser",
    publisher: "Travian Games",
    developer: "Travian Games",
    release_date: "2004-09-05",
    freetogame_profile_url: "https://www.freetogame.com/travian",
  },
  {
    id: 332,
    title: "Red Stone Online",
    thumbnail: "https://www.freetogame.com/g/332/thumbnail.jpg",
    short_description:
      "A free to play 2D old school isometric MMORPG similar to Diablo.",
    game_url: "https://www.freetogame.com/open/red-stone-online",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "L＆K CO., LTD",
    developer: "L＆K CO., LTD",
    release_date: "2003-10-06",
    freetogame_profile_url: "https://www.freetogame.com/red-stone-online",
  },
  {
    id: 432,
    title: "Habbo",
    thumbnail: "https://www.freetogame.com/g/432/thumbnail.jpg",
    short_description: "One of the largest and most popular Social MMO.",
    game_url: "https://www.freetogame.com/open/habbo",
    genre: "Social",
    platform: "Web Browser",
    publisher: "Sulake Corporation",
    developer: "Sulake Corporation",
    release_date: "2001-09-26",
    freetogame_profile_url: "https://www.freetogame.com/habbo",
  },
  {
    id: 339,
    title: "Tibia",
    thumbnail: "https://www.freetogame.com/g/339/thumbnail.jpg",
    short_description:
      "A old-school free-to-play massively multiplayer online \r\nrole-playing game.",
    game_url: "https://www.freetogame.com/open/tibia",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "CipSoft",
    developer: "CipSoft",
    release_date: "1997-01-07",
    freetogame_profile_url: "https://www.freetogame.com/tibia",
  },
];
